### ISSUE TITLE
Submitters of KGE File Sets should  be  allowed  to somehow update/repair file sets that they "own"

### ISSUE THREAD

**Issue by RichardBruskiewich** [NCATSTranslator/Knowledge_Graph_Exchange_Registry#36]
Submitters of KGE File Sets should be allowed to somehow update/repair file sets that they "own",  including repair of the metadata files or other  related  modifications (e.g.  change  the submitter,  updated the  description, etc....  i.e.  a metadata editor)

**Comment by jeffhhk** [comment]
My preference would be for the users to have to create a new minor version number to change versions that have already been published.  Append-only data sources are simpler to consume.

The one thing that I think would be useful to change after the fact is a simple "deprecated" boolean, default false, to be asserted when some problem is found with a previously published version.

**Comment by RichardBruskiewich** [comment]
Duplicate of https://github.com/NCATSTranslator/Knowledge_Graph_Exchange_Registry/issues/22
