### ISSUE TITLE
.tsv upload crashes KGE backend

### ISSUE THREAD

**Issue by jeffhhk** [NCATSTranslator/Knowledge_Graph_Exchange_Registry#51]
Repro:

1) Create a new fileset for yeast-sri-reference-kg-tsv
2) Upload nodes.tsv
3) Upload edges.tsv
4) Click "Done Uploading"

Result:

GET https://archive.translator.ncats.io/archive/publish/yeast-sri-reference-kg-tsv/1.3
HTTP status 504 Gateway Timeout

**Comment by jeffhhk** [comment]
This morning in response to clicking "Done Uploading", I got the following HTTP status 200 confirmation in around 6.5 seconds:

> Confirmation of Submission
>
> File Set '1.9' of 'yeast-sri-reference-kg-tsv' submitted by 'Jeff Henrikson' is being processed and should soon be available for downloading from the home page .

So regarding the HTTP request staying open for the duration of processing, this issue is resolved.

There may be remaining issues with OOM during processing itself.  I will leave it to your discretion whether or not to leave this issue open as-is or close and open a new more specific issue for OOM during processing.

**Comment by RichardBruskiewich** [comment]
Fixed(?)
